config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  
  post '/login', to: 'welcome#login'


  resources :users
  resources :ais_vessal_destinations
  resources :ais_trackings
  resources :port_vessels
  resources :vessels
  # get 'articles/new'
  # get 'welcome', to: 'welcome#index'
  # get 'welcome/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ais_tracking.rb
class AisTracking < ApplicationRecord
  belongs_to :vessel
  
  validates :heading, presence: true
  
  before_validation :ensure_heading_has_value
  
  private
    def ensure_heading_has_value
      if heading.nil?
        self.heading = "aaaa"
      end
    end
end

app/controllers/ais_trackings_controller.rb
class AisTrackingsController < ApplicationController
  before_action :set_ais_tracking, only: [:show, :edit, :update, :destroy]

  # GET /ais_trackings
  # GET /ais_trackings.json
  def index
    @ais_trackings = AisTracking.all
  end

  # GET /ais_trackings/1
  # GET /ais_trackings/1.json
  def show
  end

  # GET /ais_trackings/new
  def new
    @ais_tracking = AisTracking.new
  end

  # GET /ais_trackings/1/edit
  def edit
  end

  # POST /ais_trackings
  # POST /ais_trackings.json
  def create
    @ais_tracking = AisTracking.new(ais_tracking_params)

    respond_to do |format|
      if @ais_tracking.save
        format.html { redirect_to @ais_tracking, notice: 'Ais tracking was successfully created.' }
        format.json { render :show, status: :created, location: @ais_tracking }
      else
        format.html { render :new }
        format.json { render json: @ais_tracking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ais_trackings/1
  # PATCH/PUT /ais_trackings/1.json
  def update
    respond_to do |format|
      if @ais_tracking.update(ais_tracking_params)
        format.html { redirect_to @ais_tracking, notice: 'Ais tracking was successfully updated.' }
        format.json { render :show, status: :ok, location: @ais_tracking }
      else
        format.html { render :edit }
        format.json { render json: @ais_tracking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ais_trackings/1
  # DELETE /ais_trackings/1.json
  def destroy
    @ais_tracking.destroy
    respond_to do |format|
      format.html { redirect_to ais_trackings_url, notice: 'Ais tracking was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ais_tracking
      @ais_tracking = AisTracking.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ais_tracking_params
      params.require(:ais_tracking).permit(:latitude, :longtitude, :heading, :speed_over_ground, :last_ais_updated_at, :nav_status_code, :vessel_id, :course, :collection_type)
    end
end

app/helpers/ais_trackings_helper.rb
module AisTrackingsHelper
  def full_title(param = '')
    if param.empty?
      param = "begin with helper"
    end
  end
end

app/views/ais_trackings/_form.html.haml
= form_with(model: ais_tracking, local: true) do |form|
  - if ais_tracking.errors.any?
    #error_explanation
      %h2
        = pluralize(ais_tracking.errors.count, "error")
        prohibited this ais_tracking from being saved:
      %ul
        - ais_tracking.errors.full_messages.each do |message|
          %li= message
  .field
    = form.label :latitude
    = form.text_field :latitude, id: :ais_tracking_latitude
  .field
    = form.label :longtitude
    = form.text_field :longtitude, id: :ais_tracking_longtitude
  .field
    = form.label :heading
    = form.number_field :heading, id: :ais_tracking_heading
  .field
    = form.label :speed_over_ground
    = form.text_field :speed_over_ground, id: :ais_tracking_speed_over_ground
  .field
    = form.label :last_ais_updated_at
    = form.datetime_select :last_ais_updated_at, id: :ais_tracking_last_ais_updated_at
  .field
    = form.label :nav_status_code
    = form.number_field :nav_status_code, id: :ais_tracking_nav_status_code
  .field
    = form.label :vessel_id
    = form.number_field :vessel_id, id: :ais_tracking_vessel_id
  .field
    = form.label :course
    = form.text_field :course, id: :ais_tracking_course
  .field
    = form.label :collection_type
    = form.number_field :collection_type, id: :ais_tracking_collection_type
  .actions
    = form.submit

app/views/ais_trackings/edit.html.haml
%h1 Editing Ais Tracking
= render 'form', ais_tracking: @ais_tracking
= link_to 'Show', @ais_tracking
|
= link_to 'Back', ais_trackings_path

app/views/ais_trackings/index.html.haml
%p#notice= notice
%h1
  = full_title('')
  Ais Trackings
%table
  %thead
    %tr
      %th Latitude
      %th Longtitude
      %th Heading
      %th Speed over ground
      %th Last ais updated at
      %th Nav status code
      %th Vessel
      %th Course
      %th Collection type
      %th{:colspan => "3"}
  %tbody
    - @ais_trackings.each do |ais_tracking|
      %tr
        %td= ais_tracking.latitude
        %td= ais_tracking.longtitude
        %td= ais_tracking.heading
        %td= ais_tracking.speed_over_ground
        %td= ais_tracking.last_ais_updated_at
        %td= ais_tracking.nav_status_code
        %td= ais_tracking.vessel_id
        %td= ais_tracking.course
        %td= ais_tracking.collection_type
        %td= link_to 'Show', ais_tracking
        %td= link_to 'Edit', edit_ais_tracking_path(ais_tracking)
        %td= link_to 'Destroy', ais_tracking, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Ais Tracking', new_ais_tracking_path

app/views/ais_trackings/new.html.haml
%h1
  = full_title('aaa')
  New Ais Tracking
= render 'form', ais_tracking: @ais_tracking
= link_to 'Back', ais_trackings_path

app/views/ais_trackings/show.html.haml
%p#notice= notice
%p
  %strong Latitude:
  = @ais_tracking.latitude
%p
  %strong Longtitude:
  = @ais_tracking.longtitude
%p
  %strong Heading:
  = @ais_tracking.heading
%p
  %strong Speed over ground:
  = @ais_tracking.speed_over_ground
%p
  %strong Last ais updated at:
  = @ais_tracking.last_ais_updated_at
%p
  %strong Nav status code:
  = @ais_tracking.nav_status_code
%p
  %strong Vessel:
  = @ais_tracking.vessel_id
%p
  %strong Course:
  = @ais_tracking.course
%p
  %strong Collection type:
  = @ais_tracking.collection_type
= link_to 'Edit', edit_ais_tracking_path(@ais_tracking)
|
= link_to 'Back', ais_trackings_path