config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  
  post '/login', to: 'welcome#login'


  resources :users
  resources :ais_vessal_destinations
  resources :ais_trackings
  resources :port_vessels
  resources :vessels
  # get 'articles/new'
  # get 'welcome', to: 'welcome#index'
  # get 'welcome/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/vessel.rb
class Vessel < ApplicationRecord
  has_many :ais_trackings
  has_many :ais_vessal_destinations
  has_many :port_vessels
  
  scope :vessel_in_day, -> { where("mmsi = ?", "tuyet")}
  
  def self.getMMSI(ais_trackings)
  
  end
  
  
  validates :imo, :mmsi,
            presence: {message: 'cannot be null'}
  validates :imo,
            uniqueness: {
                scope: :mmsi,
                message: 'cannot be duplicate'}
  
end

app/controllers/vessels_controller.rb
class VesselsController < ApplicationController
  before_action :set_vessel, only: [:show, :edit, :update, :destroy]

  # GET /vessels
  # GET /vessels.json
  def index
    @vessels = Vessel.all
  end

  # GET /vessels/1
  # GET /vessels/1.json
  def show
  end

  # GET /vessels/new
  def new
    @vessel = Vessel.new
  end

  # GET /vessels/1/edit
  def edit
  end

  # POST /vessels
  # POST /vessels.json
  def create
    @vessel = Vessel.new(vessel_params)

    respond_to do |format|
      if @vessel.save
        format.html { redirect_to @vessel, notice: 'Vessel was successfully created.' }
        format.json { render :show, status: :created, location: @vessel }
      else
        format.html { render :new }
        format.json { render json: @vessel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vessels/1
  # PATCH/PUT /vessels/1.json
  def update
    respond_to do |format|
      if @vessel.update(vessel_params)
        format.html { redirect_to @vessel, notice: 'Vessel was successfully updated.' }
        format.json { render :show, status: :ok, location: @vessel }
      else
        format.html { render :edit }
        format.json { render json: @vessel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vessels/1
  # DELETE /vessels/1.json
  def destroy
    @vessel.destroy
    respond_to do |format|
      format.html { redirect_to vessels_url, notice: 'Vessel was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vessel
      @vessel = Vessel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vessel_params
      params.require(:vessel).permit(:status, :mmsi, :imo, :name, :callsign, :vessel_type, :vessel_class, :company_id, :line_id, :raw_data, :slug, :active)
    end
end

app/helpers/vessels_helper.rb
module VesselsHelper
end

app/views/vessels/_form.html.haml
= form_with(model: vessel, local: true) do |form|
  - if vessel.errors.any?
    #error_explanation
      %h2
        = pluralize(vessel.errors.count, "error")
        prohibited this vessel from being saved:
      %ul
        - vessel.errors.full_messages.each do |message|
          %li= message
  .field
    = form.label :status
    = form.number_field :status, id: :vessel_status
  .field
    = form.label :mmsi
    = form.text_field :mmsi, id: :vessel_mmsi
  .field
    = form.label :imo
    = form.text_field :imo, id: :vessel_imo
  .field
    = form.label :name
    = form.text_field :name, id: :vessel_name
  .field
    = form.label :callsign
    = form.text_field :callsign, id: :vessel_callsign
  .field
    = form.label :vessel_type
    = form.text_field :vessel_type, id: :vessel_vessel_type
  .field
    = form.label :vessel_class
    = form.text_field :vessel_class, id: :vessel_vessel_class
  .field
    = form.label :company_id
    = form.number_field :company_id, id: :vessel_company_id
  .field
    = form.label :line_id
    = form.number_field :line_id, id: :vessel_line_id
  .field
    = form.label :raw_data
    = form.number_field :raw_data, id: :vessel_raw_data
  .field
    = form.label :slug
    = form.text_field :slug, id: :vessel_slug
  .field
    = form.label :active
    = form.check_box :active, id: :vessel_active
  .actions
    = form.submit

app/views/vessels/edit.html.haml
%h1 Editing Vessel
= render 'form', vessel: @vessel
= link_to 'Show', @vessel
|
= link_to 'Back', vessels_path

app/views/vessels/index.html.haml
%p#notice= notice
%h1 Vessels
%table.table-of-contents
  %thead
    %tr
      %th Status
      %th Mmsi
      %th Imo
      %th Name
      %th Callsign
      %th Vessel type
      %th Vessel class
      %th Company
      %th Line
      %th Raw data
      %th Slug
      %th Active
      %th{:colspan => "3"}
  %tbody
    - @vessels.each do |vessel|
      %tr
        %td= vessel.status
        %td= vessel.mmsi
        %td= vessel.imo
        %td= vessel.name
        %td= vessel.callsign
        %td= vessel.vessel_type
        %td= vessel.vessel_class
        %td= vessel.company_id
        %td= vessel.line_id
        %td= vessel.raw_data
        %td= vessel.slug
        %td= vessel.active
        %td= link_to 'Show', vessel
        %td= link_to 'Edit', edit_vessel_path(vessel)
        %td= link_to 'Destroy', vessel, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Vessel', new_vessel_path

app/views/vessels/new.html.haml
%h1 New Vessel
= render 'form', vessel: @vessel
= link_to 'Back', vessels_path

app/views/vessels/show.html.haml
%p#notice= notice
%p
  %strong Status:
  = @vessel.status
%p
  %strong Mmsi:
  = @vessel.mmsi
%p
  %strong Imo:
  = @vessel.imo
%p
  %strong Name:
  = @vessel.name
%p
  %strong Callsign:
  = @vessel.callsign
%p
  %strong Vessel type:
  = @vessel.vessel_type
%p
  %strong Vessel class:
  = @vessel.vessel_class
%p
  %strong Company:
  = @vessel.company_id
%p
  %strong Line:
  = @vessel.line_id
%p
  %strong Raw data:
  = @vessel.raw_data
%p
  %strong Slug:
  = @vessel.slug
%p
  %strong Active:
  = @vessel.active
= link_to 'Edit', edit_vessel_path(@vessel)
|
= link_to 'Back', vessels_path