config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  
  post '/login', to: 'welcome#login'


  resources :users
  resources :ais_vessal_destinations
  resources :ais_trackings
  resources :port_vessels
  resources :vessels
  # get 'articles/new'
  # get 'welcome', to: 'welcome#index'
  # get 'welcome/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/port_vessel.rb
class PortVessel < ApplicationRecord
  belongs_to :vessel
end

app/controllers/port_vessels_controller.rb
class PortVesselsController < ApplicationController
  before_action :set_port_vessel, only: [:show, :edit, :update, :destroy]

  # GET /port_vessels
  # GET /port_vessels.json
  def index
    @port_vessels = PortVessel.all
  end

  # GET /port_vessels/1
  # GET /port_vessels/1.json
  def show
  end

  # GET /port_vessels/new
  def new
    @port_vessel = PortVessel.new
  end

  # GET /port_vessels/1/edit
  def edit
  end

  # POST /port_vessels
  # POST /port_vessels.json
  def create
    @port_vessel = PortVessel.new(port_vessel_params)

    respond_to do |format|
      if @port_vessel.save
        format.html { redirect_to @port_vessel, notice: 'Port vessel was successfully created.' }
        format.json { render :show, status: :created, location: @port_vessel }
      else
        format.html { render :new }
        format.json { render json: @port_vessel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /port_vessels/1
  # PATCH/PUT /port_vessels/1.json
  def update
    respond_to do |format|
      if @port_vessel.update(port_vessel_params)
        format.html { redirect_to @port_vessel, notice: 'Port vessel was successfully updated.' }
        format.json { render :show, status: :ok, location: @port_vessel }
      else
        format.html { render :edit }
        format.json { render json: @port_vessel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /port_vessels/1
  # DELETE /port_vessels/1.json
  def destroy
    @port_vessel.destroy
    respond_to do |format|
      format.html { redirect_to port_vessels_url, notice: 'Port vessel was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_port_vessel
      @port_vessel = PortVessel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def port_vessel_params
      params.require(:port_vessel).permit(:port_id, :vessel_id, :last_position_updated_at, :nav_status_code)
    end
end

app/helpers/port_vessels_helper.rb
module PortVesselsHelper
end

app/views/port_vessels/_form.html.haml
= form_with(model: port_vessel, local: true) do |form|
  - if port_vessel.errors.any?
    #error_explanation
      %h2
        = pluralize(port_vessel.errors.count, "error")
        prohibited this port_vessel from being saved:
      %ul
        - port_vessel.errors.full_messages.each do |message|
          %li= message
  .field
    = form.label :port_id
    = form.number_field :port_id, id: :port_vessel_port_id
  .field
    = form.label :vessel_id
    = form.number_field :vessel_id, id: :port_vessel_vessel_id
  .field
    = form.label :last_position_updated_at
    = form.datetime_select :last_position_updated_at, id: :port_vessel_last_position_updated_at
  .field
    = form.label :nav_status_code
    = form.number_field :nav_status_code, id: :port_vessel_nav_status_code
  .actions
    = form.submit

app/views/port_vessels/edit.html.haml
%h1 Editing Port Vessel
= render 'form', port_vessel: @port_vessel
= link_to 'Show', @port_vessel
|
= link_to 'Back', port_vessels_path

app/views/port_vessels/index.html.haml
%p#notice= notice
%h1 Port Vessels
%table
  %thead
    %tr
      %th Port
      %th Vessel
      %th Last position updated at
      %th Nav status code
      %th{:colspan => "3"}
  %tbody
    - @port_vessels.each do |port_vessel|
      %tr
        %td= port_vessel.port_id
        %td= port_vessel.vessel_id
        %td= port_vessel.last_position_updated_at
        %td= port_vessel.nav_status_code
        %td= link_to 'Show', port_vessel
        %td= link_to 'Edit', edit_port_vessel_path(port_vessel)
        %td= link_to 'Destroy', port_vessel, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Port Vessel', new_port_vessel_path

app/views/port_vessels/new.html.haml
%h1 New Port Vessel
= render 'form', port_vessel: @port_vessel
= link_to 'Back', port_vessels_path

app/views/port_vessels/show.html.haml
%p#notice= notice
%p
  %strong Port:
  = @port_vessel.port_id
%p
  %strong Vessel:
  = @port_vessel.vessel_id
%p
  %strong Last position updated at:
  = @port_vessel.last_position_updated_at
%p
  %strong Nav status code:
  = @port_vessel.nav_status_code
= link_to 'Edit', edit_port_vessel_path(@port_vessel)
|
= link_to 'Back', port_vessels_path